/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mwe;
import lombok.extern.java.Log;

@Log
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
